const ACTION_TYPE={
    SEARCH:"SEARCH",
    CATEGORY:"CATEGORY",
    RANGE:"FILTER_BY_RANGE",
    RATE:"FILTER_BY_RATE",
    RESET:"RESET",
    ADD_TO_LIKE:"ADD_TO_LIKE",
    GET_LIKE:"GET_LIKE",
    REMOVE_FROM_LIKE:"REMOVE_FROM_LIKE",
    ADD_TO_WISHLIST:"ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST:"REMOVE_FROM_WISHLIST",
    CLEAR_CART:"CLEAR_CART"
}

export {ACTION_TYPE}